version: '3.7'

services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=konga
      - POSTGRES_PASSWORD=konga
      - POSTGRES_DB=konga
    networks:
      - default

  konga:
    image: pantsel/konga:latest
    ports:
      - 1337:1337
    environment:
      - TOKEN_SECRET=loremipsum
      - DB_ADAPTER=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=konga
      - DB_PASSWORD=konga
      - DB_DATABASE=konga
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - default

volumes:
  postgres:

networks:
  default:
